name: server_manager
description: Server Status Manager

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # =========================================================================
  # System                                                                  #
  # =========================================================================
  intl: ^0.18.1
  # reference - https://pub.dev/packages/intl
  # descryption - utility
  get: ^4.6.5
  # https://pub.dev/packages/get_storage
  # descryption - state manager
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # https://pub.dev/packages/hive
  # descryption - local DB
  hive_generator: ^2.0.1
  # https://pub.dev/packages/hive_generator
  # descryption - local DB
  source_span: ^1.8.2
  # reference - https://pub.dev/packages/source_span
  # descryption - source formatting
  change_app_package_name: ^1.1.0
  # reference - https://pub.dev/packages/change_app_package_name
  # descryption - packagename change
  webview_flutter: ^4.2.3
  # reference - https://pub.dev/packages/webview_flutter
  # descryption - webview widget


  # =========================================================================
  # Authorization                                                           #
  # =========================================================================
  google_sign_in: ^6.1.6
  # reference - https://pub.dev/packages/google_sign_in
  # descryption - Google account login
  firebase_core: ^2.24.2
  # reference - https://pub.dev/packages/firebase_core
  # descryption - Firebase Function
  firebase_auth: ^4.6.3
  # reference - https://pub.dev/packages/firebase_auth
  # descryption - Firebase Auth



  # =========================================================================
  # Network                                                                 #
  # =========================================================================
  http: ^1.1.0
  # reference - https://pub.dev/packages/http
  # descryption - making HTTP requests.
  json_serializable: ^6.7.1
  # reference - https://pub.dev/packages/json_serializable
  # descryption - builders for handling JSON
  dio: ^5.3.2
  # reference - https://pub.dev/packages/dio
  # descryption - Http client for Dart, which supports Interceptors, Global configuration, FormData, Request Cancellation, File downloading, Timeout etc.


  # =========================================================================
  # ui                                                                      #
  # =========================================================================
  cupertino_icons: ^1.0.2
  # reference - https://pub.dev/packages/cupertino_icons
  # descryption - iOS style icon
  google_fonts: ^5.1.0
  # reference - https://pub.dev/packages/google_fonts
  # descryption - font
  font_awesome_flutter: ^10.1.0
  # reference - https://pub.dev/packages/font_awesome_flutter
  # descryption - font
  dialogs: ^0.0.7
  # reference - https://pub.dev/packages/dialogs
  # descryption - dialog design
  flutter_custom_dialog: ^1.3.0
  # reference - https://pub.dev/packages/flutter_custom_dialog
  # descryption - dialog
  flutter_screenutil: ^5.9.0
  # reference - https://pub.dev/packages/flutter_screenutil
  # descryption - ui concept
  pin_code_fields: ^8.0.1
  # reference - https://pub.dev/packages/pin_code_fields
  # descryption - pin code widget


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  # reference - https://pub.dev/packages/flutter_lints
  # descryption - lint setup (analysis_options.yaml)
  build_runner: ^2.2.1
  # reference - https://pub.dev/packages/build_runner
  # descryption - generating files using Dart code

flutter:

  uses-material-design: true