// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbW_MSmQp2YQtXbnJQqIXL9RR7CR4G03c',
    appId: '1:743545271636:web:bb92ce948a52263d2984c1',
    messagingSenderId: '743545271636',
    projectId: 'adminmanager-13614',
    authDomain: 'adminmanager-13614.firebaseapp.com',
    storageBucket: 'adminmanager-13614.appspot.com',
    measurementId: 'G-Z33N6B9TEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWj74SyzRiULQPIfykE9I431PR0_LNjY4',
    appId: '1:743545271636:android:5d9f1d361b24265a2984c1',
    messagingSenderId: '743545271636',
    projectId: 'adminmanager-13614',
    storageBucket: 'adminmanager-13614.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYa5PFVEwDAwa002oIna4sHTJOFF2DDz4',
    appId: '1:743545271636:ios:f31b50c2ee0140fa2984c1',
    messagingSenderId: '743545271636',
    projectId: 'adminmanager-13614',
    storageBucket: 'adminmanager-13614.appspot.com',
    iosBundleId: 'bonacamp.se.systemmanager.serverManager',
  );
}
